# All subfolders will be made in this directory
baseLocation: C:/Users/dell/Documents/projects/dev
# These are the subfolders/ subcategories in which projects are made
# The 'name' will be used in a templates' 'type' argument
folders:
  - name: node.js
    folder: 'nodejs'
# Just sequences of actions to do
# Eg. Setup workspace by opening Chrome, VS Code, Terminal etc.
actions:
  - name: demo action
    arguments: # arguments are fields which require manualinput in order to run the action
      - name
    commands:
      - echo this is a sample action
      - echo hello $name #argument is specified like this
  - name: demo2
    arguments:
      - age
    commands:
      - echo Your age is $age
# Here, templates for projects are made
# They will be automatically be setup since u specify what the category of the project is and the steps
# A new folder with the name specified will automatically be made and all commands are run in it
projectTemplates:
  - name: Basic node.js
    arguments:
      - name
      - type
    commands:
      - npm init -y